name: GHA implementation with Kafka
on:
  repository_dispatch:
    types: [gha-kafka]

jobs:
  async_job:
    runs-on: self-hosted
    steps:
    - name: Hit Async Api
      run: echo "https://async.api.com/create/${{ github.event.client_payload.id }}"
      
    - name: Trigger kafka listener
      run: python3 /home/ec2-user/listener.py {{ github.event.client_payload.id }}
      shell: bash
