name: Demo workflow to set async job status based on event

on:
  repository_dispatch:
    types: [async-job]

jobs:
  set_aync_job_status:
    runs-on: self-hosted
    name: async_job
    steps:
      - name: Print job ID
        run: echo "Current job ID is ${{ github.job }}"
      
      - name: Set async job status step
        id: async_step
        uses: BlackHat786000/set-async-job-status@v2.7
        with:
          kafka_broker: '65.2.151.189:9092'
          topic_name: 'myFirstJsonTopic'
          job_id: ${{ github.job }}
          listener_timeout: 5
